server:
  port: 9990
dubbo:
  application:
    name: back_product
  registry:
    protocol: zookeeper
    address: 47.102.213.220:2181
  provider:
    timeout: 1200000

spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 47.102.213.220:22122

image:
  server: http://47.102.213.220/