server:
  port: 8880

spring:
  profiles:
    active: product_service
  datasource:
    url: jdbc:mysql://47.102.213.220:3306/v16?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: jiang,111
    driver-class-name: com.mysql.jdbc.Driver
  provider:
    timeout: 1200000
dubbo:
  application:
    name: product_service
  registry:
    protocol: zookeeper
    address: 47.102.213.220:2181
  protocol:
    port: 28811

